-- Sprint 1 core multiplayer migration for GAL Castle Escape.
-- Run this in the Supabase SQL editor before using index.html / teacher.html.
-- This migration is stricter than the Three Doors demo:
-- - no public table DELETE/reset
-- - browser code uses publishable key only
-- - students act through session-token RPC functions
-- - teacher actions require a room-specific teacher token
-- - private choices are hidden from teacher until reveal

create extension if not exists pgcrypto;

create table if not exists public.s1_rooms (
  room_code text primary key,
  teacher_token_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.s1_room_players (
  player_id uuid primary key default gen_random_uuid(),
  room_code text not null references public.s1_rooms(room_code) on delete cascade,
  role_slot text not null check (role_slot in ('GAL-A','GAL-B','GAL-C')),
  display_name text not null,
  join_code_hash text not null,
  session_token_hash text,
  joined_at timestamptz,
  last_seen_at timestamptz,
  unique (room_code, role_slot)
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 's1_room_players_room_join_code_hash_unique'
      and conrelid = 'public.s1_room_players'::regclass
  ) then
    alter table public.s1_room_players
      add constraint s1_room_players_room_join_code_hash_unique unique (room_code, join_code_hash);
  end if;
end;
$$;

create table if not exists public.s1_scene_choices (
  scene_id integer not null,
  choice_id text not null,
  choice_label text not null,
  active boolean not null default true,
  primary key (scene_id, choice_id)
);

create table if not exists public.s1_room_state (
  room_code text primary key references public.s1_rooms(room_code) on delete cascade,
  current_scene integer not null default 1,
  phase text not null default 'collecting' check (phase in ('collecting','revealed','completed')),
  updated_at timestamptz not null default now()
);

create table if not exists public.s1_player_decisions (
  decision_id bigint generated by default as identity primary key,
  room_code text not null references public.s1_rooms(room_code) on delete cascade,
  scene_id integer not null,
  player_id uuid not null references public.s1_room_players(player_id) on delete cascade,
  decision_type text not null default 'private_choice',
  choice_id text not null,
  choice_label text not null,
  locked_at timestamptz not null default now(),
  unique (room_code, scene_id, player_id, decision_type)
);

create table if not exists public.s1_game_events (
  event_id bigint generated by default as identity primary key,
  room_code text not null references public.s1_rooms(room_code) on delete cascade,
  event_type text not null,
  actor_player_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.s1_rooms enable row level security;
alter table public.s1_room_players enable row level security;
alter table public.s1_scene_choices enable row level security;
alter table public.s1_room_state enable row level security;
alter table public.s1_player_decisions enable row level security;
alter table public.s1_game_events enable row level security;

-- No broad table policies are added in Sprint 1. Browser access goes through
-- SECURITY DEFINER functions below.

insert into public.s1_scene_choices(scene_id, choice_id, choice_label, active)
values
  (1, 'map', 'Study the map on the wall', true),
  (1, 'keys', 'Check the old keys on the desk', true),
  (1, 'door', 'Go straight to the door', true),
  (2, 'run', 'Run toward the corridor', true),
  (2, 'hide', 'Hide and listen', true),
  (2, 'call', 'Call for the others', true)
on conflict (scene_id, choice_id) do update
set choice_label = excluded.choice_label,
    active = excluded.active;

create or replace function public.s1_hash_token(value text)
returns text
language sql
stable
as $$
  select encode(digest(value, 'sha256'), 'hex')
$$;

create or replace function public.s1_touch_room(p_room_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.s1_rooms
  set updated_at = now()
  where room_code = upper(trim(p_room_code));
end;
$$;

create or replace function public.s1_assert_teacher(p_room_code text, p_teacher_token text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.s1_rooms
    where room_code = upper(trim(p_room_code))
      and teacher_token_hash = public.s1_hash_token(p_teacher_token)
  ) then
    raise exception 'Invalid teacher token for this room.';
  end if;
end;
$$;

create or replace function public.s1_create_room(
  p_room_code text,
  p_teacher_token text,
  p_gitte_join_code text,
  p_anna_join_code text,
  p_linda_join_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
begin
  if v_room_code = '' or trim(coalesce(p_teacher_token, '')) = '' then
    raise exception 'Room code and teacher token are required.';
  end if;

  if trim(coalesce(p_gitte_join_code, '')) = ''
     or trim(coalesce(p_anna_join_code, '')) = ''
     or trim(coalesce(p_linda_join_code, '')) = '' then
    raise exception 'All three join codes are required.';
  end if;

  if public.s1_hash_token(p_gitte_join_code) = public.s1_hash_token(p_anna_join_code)
     or public.s1_hash_token(p_gitte_join_code) = public.s1_hash_token(p_linda_join_code)
     or public.s1_hash_token(p_anna_join_code) = public.s1_hash_token(p_linda_join_code) then
    raise exception 'Join codes must be mutually distinct.';
  end if;

  if exists (select 1 from public.s1_rooms where room_code = v_room_code) then
    raise exception 'Room already exists. Use Watch room with the existing teacher token, or use a future teacher-authenticated reinitialize action.';
  end if;

  insert into public.s1_rooms(room_code, teacher_token_hash)
  values (v_room_code, public.s1_hash_token(p_teacher_token));

  insert into public.s1_room_state(room_code, current_scene, phase)
  values (v_room_code, 1, 'collecting');

  insert into public.s1_room_players(room_code, role_slot, display_name, join_code_hash)
  values
    (v_room_code, 'GAL-A', 'Gitte', public.s1_hash_token(p_gitte_join_code)),
    (v_room_code, 'GAL-B', 'Anna', public.s1_hash_token(p_anna_join_code)),
    (v_room_code, 'GAL-C', 'Linda', public.s1_hash_token(p_linda_join_code));

  insert into public.s1_game_events(room_code, event_type, details)
  values (v_room_code, 'room_created', '{}'::jsonb);

  return jsonb_build_object('room_code', v_room_code, 'ok', true);
end;
$$;

create or replace function public.s1_join_player(p_room_code text, p_join_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_token text := gen_random_uuid()::text;
begin
  if v_room_code = '' or trim(coalesce(p_join_code, '')) = '' then
    raise exception 'Room code and join code are required.';
  end if;

  select *
  into v_player
  from public.s1_room_players
  where room_code = v_room_code
    and join_code_hash = public.s1_hash_token(p_join_code);

  if not found then
    raise exception 'Invalid room code or join code.';
  end if;

  if v_player.session_token_hash is not null then
    raise exception 'This role is already claimed. Reopen the original browser session, or ask the teacher to release this player session.';
  end if;

  update public.s1_room_players
  set session_token_hash = public.s1_hash_token(v_token),
      joined_at = coalesce(joined_at, now()),
      last_seen_at = now()
  where player_id = v_player.player_id;

  insert into public.s1_game_events(room_code, event_type, actor_player_id, details)
  values (v_room_code, 'player_joined', v_player.player_id, jsonb_build_object('role_slot', v_player.role_slot));

  return jsonb_build_object(
    'room_code', v_room_code,
    'player_id', v_player.player_id,
    'role_slot', v_player.role_slot,
    'display_name', v_player.display_name,
    'session_token', v_token
  );
end;
$$;

create or replace function public.s1_get_player_by_session(p_room_code text, p_session_token text)
returns public.s1_room_players
language plpgsql
security definer
set search_path = public
as $$
declare
  v_player public.s1_room_players%rowtype;
begin
  select *
  into v_player
  from public.s1_room_players
  where room_code = upper(trim(p_room_code))
    and session_token_hash = public.s1_hash_token(p_session_token);

  if not found then
    raise exception 'Invalid or expired player session.';
  end if;

  update public.s1_room_players
  set last_seen_at = now()
  where player_id = v_player.player_id;

  return v_player;
end;
$$;

create or replace function public.s1_get_player_state(p_room_code text, p_session_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_state public.s1_room_state%rowtype;
  v_submitted_count integer;
  v_my_decision jsonb;
  v_revealed jsonb := '[]'::jsonb;
begin
  v_player := public.s1_get_player_by_session(v_room_code, p_session_token);

  select *
  into v_state
  from public.s1_room_state
  where room_code = v_room_code;

  select count(*)
  into v_submitted_count
  from public.s1_player_decisions
  where room_code = v_room_code
    and scene_id = v_state.current_scene
    and decision_type = 'private_choice';

  select to_jsonb(d)
  into v_my_decision
  from public.s1_player_decisions d
  where d.room_code = v_room_code
    and d.scene_id = v_state.current_scene
    and d.player_id = v_player.player_id
    and d.decision_type = 'private_choice';

  if v_state.phase in ('revealed','completed') then
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_id', p.player_id,
      'display_name', p.display_name,
      'role_slot', p.role_slot,
      'choice_id', d.choice_id,
      'choice_label', d.choice_label,
      'locked_at', d.locked_at
    ) order by p.role_slot), '[]'::jsonb)
    into v_revealed
    from public.s1_player_decisions d
    join public.s1_room_players p on p.player_id = d.player_id
    where d.room_code = v_room_code
      and d.scene_id = v_state.current_scene
      and d.decision_type = 'private_choice';
  end if;

  return jsonb_build_object(
    'room_code', v_room_code,
    'player_id', v_player.player_id,
    'display_name', v_player.display_name,
    'role_slot', v_player.role_slot,
    'current_scene', v_state.current_scene,
    'phase', v_state.phase,
    'submitted_count', v_submitted_count,
    'my_decision', v_my_decision,
    'revealed_decisions', v_revealed
  );
end;
$$;

create or replace function public.s1_submit_private_choice(
  p_room_code text,
  p_session_token text,
  p_choice_id text,
  p_choice_label text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_state public.s1_room_state%rowtype;
  v_submitted_count integer;
  v_choice_label text;
begin
  v_player := public.s1_get_player_by_session(v_room_code, p_session_token);

  select *
  into v_state
  from public.s1_room_state
  where room_code = v_room_code
  for update;

  if v_state.phase <> 'collecting' then
    raise exception 'This scene is no longer accepting private choices.';
  end if;

  select choice_label
  into v_choice_label
  from public.s1_scene_choices
  where scene_id = v_state.current_scene
    and choice_id = p_choice_id
    and active = true;

  if not found then
    raise exception 'Invalid choice for the current scene.';
  end if;

  insert into public.s1_player_decisions(room_code, scene_id, player_id, decision_type, choice_id, choice_label)
  values (v_room_code, v_state.current_scene, v_player.player_id, 'private_choice', p_choice_id, v_choice_label);

  insert into public.s1_game_events(room_code, event_type, actor_player_id, details)
  values (v_room_code, 'private_choice_locked', v_player.player_id, jsonb_build_object('scene_id', v_state.current_scene));

  select count(*)
  into v_submitted_count
  from public.s1_player_decisions
  where room_code = v_room_code
    and scene_id = v_state.current_scene
    and decision_type = 'private_choice';

  if v_submitted_count >= 3 then
    update public.s1_room_state
    set phase = 'revealed',
        updated_at = now()
    where room_code = v_room_code;

    insert into public.s1_game_events(room_code, event_type, details)
    values (v_room_code, 'scene_revealed', jsonb_build_object('scene_id', v_state.current_scene));
  end if;

  perform public.s1_touch_room(v_room_code);

  return jsonb_build_object('ok', true, 'submitted_count', v_submitted_count);
exception
  when unique_violation then
    raise exception 'Your first choice for this scene is already locked.';
end;
$$;

create or replace function public.s1_get_teacher_state(p_room_code text, p_teacher_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_state public.s1_room_state%rowtype;
  v_players jsonb;
  v_decisions jsonb;
begin
  perform public.s1_assert_teacher(v_room_code, p_teacher_token);

  select *
  into v_state
  from public.s1_room_state
  where room_code = v_room_code;

  select coalesce(jsonb_agg(jsonb_build_object(
    'player_id', player_id,
    'role_slot', role_slot,
    'display_name', display_name,
    'joined', joined_at is not null,
    'last_seen_at', last_seen_at
  ) order by role_slot), '[]'::jsonb)
  into v_players
  from public.s1_room_players
  where room_code = v_room_code;

  if v_state.phase in ('revealed','completed') then
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_id', player_id,
      'choice_id', choice_id,
      'choice_label', choice_label,
      'locked_at', locked_at
    )), '[]'::jsonb)
    into v_decisions
    from public.s1_player_decisions
    where room_code = v_room_code
      and scene_id = v_state.current_scene
      and decision_type = 'private_choice';
  else
    select coalesce(jsonb_agg(jsonb_build_object(
      'player_id', player_id,
      'locked_at', locked_at
    )), '[]'::jsonb)
    into v_decisions
    from public.s1_player_decisions
    where room_code = v_room_code
      and scene_id = v_state.current_scene
      and decision_type = 'private_choice';
  end if;

  return jsonb_build_object(
    'room_code', v_room_code,
    'current_scene', v_state.current_scene,
    'phase', v_state.phase,
    'players', v_players,
    'decisions', v_decisions
  );
end;
$$;

create or replace function public.s1_advance_scene(p_room_code text, p_teacher_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_state public.s1_room_state%rowtype;
begin
  perform public.s1_assert_teacher(v_room_code, p_teacher_token);

  select *
  into v_state
  from public.s1_room_state
  where room_code = v_room_code
  for update;

  if v_state.phase <> 'revealed' then
    raise exception 'Scene can only advance after reveal. Emergency override is intentionally not part of Sprint 1.';
  end if;

  if v_state.current_scene >= 2 then
    update public.s1_room_state
    set phase = 'completed',
        updated_at = now()
    where room_code = v_room_code;
  else
    update public.s1_room_state
    set current_scene = current_scene + 1,
        phase = 'collecting',
        updated_at = now()
    where room_code = v_room_code;
  end if;

  insert into public.s1_game_events(room_code, event_type, details)
  values (v_room_code, 'teacher_advanced_scene', jsonb_build_object('from_scene', v_state.current_scene));

  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.s1_release_player_session(p_room_code text, p_teacher_token text, p_role_slot text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
  v_role_slot text := upper(trim(p_role_slot));
  v_player_id uuid;
begin
  perform public.s1_assert_teacher(v_room_code, p_teacher_token);

  if v_role_slot not in ('GAL-A','GAL-B','GAL-C') then
    raise exception 'Invalid role slot.';
  end if;

  select player_id
  into v_player_id
  from public.s1_room_players
  where room_code = v_room_code
    and role_slot = v_role_slot;

  if not found then
    raise exception 'Player slot not found.';
  end if;

  update public.s1_room_players
  set session_token_hash = null,
      joined_at = null,
      last_seen_at = null
  where player_id = v_player_id;

  insert into public.s1_game_events(room_code, event_type, actor_player_id, details)
  values (v_room_code, 'teacher_released_player_session', v_player_id, jsonb_build_object('role_slot', v_role_slot));

  return jsonb_build_object('ok', true, 'role_slot', v_role_slot);
end;
$$;

create or replace function public.s1_reset_room(p_room_code text, p_teacher_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_room_code text := upper(trim(p_room_code));
begin
  perform public.s1_assert_teacher(v_room_code, p_teacher_token);

  delete from public.s1_player_decisions where room_code = v_room_code;
  update public.s1_room_state
  set current_scene = 1,
      phase = 'collecting',
      updated_at = now()
  where room_code = v_room_code;

  insert into public.s1_game_events(room_code, event_type, details)
  values (v_room_code, 'teacher_reset_room', '{}'::jsonb);

  return jsonb_build_object('ok', true);
end;
$$;

revoke execute on function public.s1_hash_token(text) from public, anon, authenticated;
revoke execute on function public.s1_touch_room(text) from public, anon, authenticated;
revoke execute on function public.s1_assert_teacher(text,text) from public, anon, authenticated;
revoke execute on function public.s1_get_player_by_session(text,text) from public, anon, authenticated;

revoke execute on function public.s1_create_room(text,text,text,text,text) from public;
revoke execute on function public.s1_join_player(text,text) from public;
revoke execute on function public.s1_get_player_state(text,text) from public;
revoke execute on function public.s1_submit_private_choice(text,text,text,text) from public;
revoke execute on function public.s1_get_teacher_state(text,text) from public;
revoke execute on function public.s1_advance_scene(text,text) from public;
revoke execute on function public.s1_release_player_session(text,text,text) from public;
revoke execute on function public.s1_reset_room(text,text) from public;

grant execute on function public.s1_create_room(text,text,text,text,text) to anon, authenticated;
grant execute on function public.s1_join_player(text,text) to anon, authenticated;
grant execute on function public.s1_get_player_state(text,text) to anon, authenticated;
grant execute on function public.s1_submit_private_choice(text,text,text,text) to anon, authenticated;
grant execute on function public.s1_get_teacher_state(text,text) to anon, authenticated;
grant execute on function public.s1_advance_scene(text,text) to anon, authenticated;
grant execute on function public.s1_release_player_session(text,text,text) to anon, authenticated;
grant execute on function public.s1_reset_room(text,text) to anon, authenticated;
