-- Independent Sprint 3B audit remediation, part 2.
-- Apply after 013_sprint3b_discussion_authority_and_request_identity.sql.
-- Covers IDA-004, IDA-006, IDA-007, IDA-008, IDA-011 and IDA-012.

alter table public.s3_runtime_scene_state
  add column if not exists allow_share_photo boolean not null default false;

alter table public.s3b_player_progress
  add column if not exists act1_action_started_at timestamptz,
  add column if not exists act1_timing_validity text not null default 'pending',
  add column if not exists first_meeting_started_at timestamptz,
  add column if not exists first_meeting_timing_validity text not null default 'pending',
  add column if not exists act4_choice_started_at timestamptz,
  add column if not exists act4_timing_validity text not null default 'pending';

alter table public.s3b_player_progress
  drop constraint if exists s3b_player_progress_act1_timing_validity_check,
  drop constraint if exists s3b_player_progress_first_meeting_timing_validity_check,
  drop constraint if exists s3b_player_progress_act4_timing_validity_check;

alter table public.s3b_player_progress
  add constraint s3b_player_progress_act1_timing_validity_check
    check(act1_timing_validity in ('pending','valid','legacy_missing_start','invalid_teacher_override')),
  add constraint s3b_player_progress_first_meeting_timing_validity_check
    check(first_meeting_timing_validity in ('pending','valid','legacy_missing_start','invalid_teacher_override')),
  add constraint s3b_player_progress_act4_timing_validity_check
    check(act4_timing_validity in ('pending','valid','legacy_missing_start','invalid_teacher_override'));

update public.s3b_player_progress
set act1_timing_validity='legacy_missing_start'
where act1_locked_at is not null and act1_action_started_at is null;
update public.s3b_player_progress
set first_meeting_timing_validity='legacy_missing_start'
where first_meeting_locked_at is not null and first_meeting_started_at is null;
update public.s3b_player_progress
set act4_timing_validity='legacy_missing_start'
where act4_locked_at is not null and act4_choice_started_at is null;

alter table public.s3b_library_attempts
  add column if not exists client_request_id uuid;

create unique index if not exists s3b_library_attempt_request_identity
  on public.s3b_library_attempts(run_id,submitted_by,client_request_id)
  where client_request_id is not null;

alter table public.runtime_events
  add column if not exists scene_id text,
  add column if not exists phase_key text,
  add column if not exists step_key text,
  add column if not exists event_source text,
  add column if not exists validity text,
  add column if not exists behavior_scoring boolean,
  add column if not exists interaction_id uuid,
  add column if not exists client_request_id uuid;

update public.runtime_events e
set scene_id=coalesce(e.scene_id,d.scene_id),
    phase_key=coalesce(e.phase_key,d.phase_key),
    step_key=coalesce(e.step_key,d.step_key),
    event_source=coalesce(e.event_source,case when e.actor_player_id is null then 'server' else 'player' end),
    validity=coalesce(e.validity,'legacy'),
    behavior_scoring=coalesce(e.behavior_scoring,
      case when e.details ? 'behavior_scoring' then (e.details->>'behavior_scoring')::boolean end),
    interaction_id=coalesce(e.interaction_id,e.discussion_session_id)
from public.discussion_sessions d
where e.discussion_session_id=d.discussion_session_id;

update public.runtime_events
set event_source=coalesce(event_source,case when actor_player_id is null then 'server' else 'player' end),
    validity=coalesce(validity,'legacy')
where event_source is null or validity is null;

create table if not exists public.s3b_post_inspection_route_votes (
  vote_id bigint generated by default as identity primary key,
  run_id uuid not null references public.game_runs(run_id),
  player_id uuid not null references public.s1_room_players(player_id),
  decision_key text not null default 'act5_post_inspection_route'
    check(decision_key='act5_post_inspection_route'),
  choice_id text not null check(choice_id in ('known','unknown')),
  decision_type text not null default 'game_only_step_vote'
    check(decision_type='game_only_step_vote'),
  behavior_scoring boolean not null default false check(not behavior_scoring),
  validity text not null default 'valid' check(validity in ('valid','invalid_teacher_override')),
  locked_at timestamptz not null default now(),
  unique(run_id,decision_key,player_id)
);

alter table public.s3b_post_inspection_route_votes enable row level security;

-- Enrich all existing event calls with authoritative context when available.
create or replace function public.s2_log_event(
  p_run_id uuid,
  p_room_code text,
  p_discussion_session_id uuid,
  p_event_type text,
  p_actor_player_id uuid,
  p_details jsonb default '{}'::jsonb
) returns void
language plpgsql security definer set search_path=public as $$
declare
  v_scene text;
  v_phase text;
  v_step text;
begin
  if p_discussion_session_id is not null then
    select scene_id,phase_key,step_key into v_scene,v_phase,v_step
    from public.discussion_sessions
    where discussion_session_id=p_discussion_session_id;
  end if;
  if v_scene is null then
    select scene_id,phase_key,step_key into v_scene,v_phase,v_step
    from public.s3_runtime_scene_state where run_id=p_run_id;
  end if;
  insert into public.runtime_events(
    run_id,room_code,discussion_session_id,event_type,actor_player_id,details,
    scene_id,phase_key,step_key,event_source,validity,behavior_scoring,interaction_id,
    client_request_id
  ) values(
    p_run_id,upper(trim(p_room_code)),p_discussion_session_id,p_event_type,
    p_actor_player_id,coalesce(p_details,'{}'::jsonb),v_scene,v_phase,v_step,
    case when p_actor_player_id is null then 'server' else 'player' end,
    coalesce(p_details->>'validity','valid'),
    case when p_details ? 'behavior_scoring' then (p_details->>'behavior_scoring')::boolean end,
    p_discussion_session_id,
    case when p_details ? 'client_request_id' then (p_details->>'client_request_id')::uuid end
  );
end;
$$;

revoke execute on function public.s2_log_event(uuid,text,uuid,text,uuid,jsonb)
  from public,anon,authenticated;

create or replace function public.s3b_log_formal_event(
  p_run_id uuid,
  p_event_type text,
  p_actor_player_id uuid,
  p_event_source text,
  p_details jsonb default '{}'::jsonb,
  p_validity text default 'valid',
  p_behavior_scoring boolean default false,
  p_interaction_id uuid default null,
  p_client_request_id uuid default null
) returns void
language plpgsql security definer set search_path=public as $$
declare
  v_room text;
  v_scene public.s3_runtime_scene_state%rowtype;
begin
  if p_event_source not in ('player','server','system_fallback','teacher_override') then
    raise exception 'Invalid formal event source.';
  end if;
  select room_code into v_room from public.game_runs where run_id=p_run_id;
  select * into v_scene from public.s3_runtime_scene_state where run_id=p_run_id;
  insert into public.runtime_events(
    run_id,room_code,discussion_session_id,event_type,actor_player_id,details,
    scene_id,phase_key,step_key,event_source,validity,behavior_scoring,
    interaction_id,client_request_id
  ) values(
    p_run_id,v_room,null,p_event_type,p_actor_player_id,coalesce(p_details,'{}'::jsonb),
    v_scene.scene_id,v_scene.phase_key,v_scene.step_key,p_event_source,p_validity,
    p_behavior_scoring,p_interaction_id,p_client_request_id
  );
end;
$$;

revoke execute on function public.s3b_log_formal_event(
  uuid,text,uuid,text,jsonb,text,boolean,uuid,uuid
) from public,anon,authenticated;

-- Scene transitions now persist permissions, timing starts and append-only
-- old/new context. Existing historical transitions are not synthesized.
create or replace function public.s3b_set_scene(
  p_run uuid,p_scene text,p_phase text,p_step text,p_mode text,p_text_key text
) returns void
language plpgsql security definer set search_path=public as $$
declare
  v_old public.s3_runtime_scene_state%rowtype;
  v_room text;
  v_allow_share boolean;
  v_had_old boolean;
begin
  if p_mode not in ('CINEMATIC_MESSAGE','CRITICAL_INFO','ACTION_SCREEN') then
    raise exception 'Invalid display mode.';
  end if;
  select * into v_old from public.s3_runtime_scene_state where run_id=p_run for update;
  v_had_old:=found;
  v_allow_share:=(p_scene='act2_first_contact' and p_phase='meeting_discussion')
    or (p_scene='act5_route_discussion' and p_phase='discussion');

  insert into public.s3_runtime_scene_state(
    run_id,scene_id,phase_key,step_key,display_mode,text_key,allow_share_photo
  ) values(p_run,p_scene,p_phase,p_step,p_mode,p_text_key,v_allow_share)
  on conflict(run_id) do update set
    scene_id=excluded.scene_id,phase_key=excluded.phase_key,step_key=excluded.step_key,
    display_mode=excluded.display_mode,text_key=excluded.text_key,
    allow_share_photo=excluded.allow_share_photo,updated_at=now();

  if p_scene='act2_first_contact' and p_phase='private_first_meeting' then
    update public.s3b_player_progress
    set first_meeting_started_at=coalesce(first_meeting_started_at,now()),
        first_meeting_timing_validity=case when first_meeting_started_at is null then 'valid' else first_meeting_timing_validity end
    where run_id=p_run and first_meeting_locked_at is null;
  elsif p_scene='act4_known_unknown' and p_phase='private_route_choice' then
    update public.s3b_player_progress
    set act4_choice_started_at=coalesce(act4_choice_started_at,now()),
        act4_timing_validity=case when act4_choice_started_at is null then 'valid' else act4_timing_validity end
    where run_id=p_run and act4_locked_at is null;
  end if;

  if not v_had_old or v_old.scene_id is distinct from p_scene
     or v_old.phase_key is distinct from p_phase
     or v_old.step_key is distinct from p_step then
    select room_code into v_room from public.game_runs where run_id=p_run;
    insert into public.runtime_events(
      run_id,room_code,event_type,details,scene_id,phase_key,step_key,
      event_source,validity,behavior_scoring
    ) values(
      p_run,v_room,'scene_transition',jsonb_build_object(
        'from_scene_id',v_old.scene_id,'from_phase_key',v_old.phase_key,
        'from_step_key',v_old.step_key,'to_scene_id',p_scene,
        'to_phase_key',p_phase,'to_step_key',p_step
      ),p_scene,p_phase,p_step,'server','valid',false
    );
  end if;
end;
$$;

-- Action wrappers preserve the deployed behavior while adding durable timing
-- and append-only evidence at the authoritative mutation boundary.
alter function public.s3b_ack_act1_opening(text,text) rename to s3b_ack_act1_opening_pre014;
alter function public.s3b_submit_act1_choice(text,text,text) rename to s3b_submit_act1_choice_pre014;
alter function public.s3b_complete_act1(text,text) rename to s3b_complete_act1_pre014;
alter function public.s3b_submit_first_meeting(text,text,text) rename to s3b_submit_first_meeting_pre014;
alter function public.s3b_grab(text,text) rename to s3b_grab_pre014;
alter function public.s3b_leave_start_room(text,text) rename to s3b_leave_start_room_pre014;
alter function public.s3b_ack_route_update(text,text) rename to s3b_ack_route_update_pre014;
alter function public.s3b_complete_foldback(text,text) rename to s3b_complete_foldback_pre014;
alter function public.s3b_follow_sign(text,text) rename to s3b_follow_sign_pre014;
alter function public.s3b_submit_act4_choice(text,text,text) rename to s3b_submit_act4_choice_pre014;

revoke execute on function public.s3b_ack_act1_opening_pre014(text,text),
  public.s3b_submit_act1_choice_pre014(text,text,text),
  public.s3b_complete_act1_pre014(text,text),
  public.s3b_submit_first_meeting_pre014(text,text,text),
  public.s3b_grab_pre014(text,text),
  public.s3b_leave_start_room_pre014(text,text),
  public.s3b_ack_route_update_pre014(text,text),
  public.s3b_complete_foldback_pre014(text,text),
  public.s3b_follow_sign_pre014(text,text),
  public.s3b_submit_act4_choice_pre014(text,text,text)
from public,anon,authenticated;

create or replace function public.s3b_ack_act1_opening(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_ack_act1_opening_pre014(p_room_code,p_session_token);
  update public.s3b_player_progress set
    act1_action_started_at=coalesce(act1_action_started_at,now()),act1_timing_validity='valid'
  where run_id=v_run.run_id and player_id=v_player.player_id;
  perform public.s3b_log_formal_event(v_run.run_id,'act1_opening_acknowledged',v_player.player_id,'player','{}', 'valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_submit_act1_choice(p_room_code text,p_session_token text,p_choice_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;v_validity text;v_duration_ms bigint;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_submit_act1_choice_pre014(p_room_code,p_session_token,p_choice_id);
  update public.s3b_player_progress set act1_timing_validity=case when act1_action_started_at is null then 'legacy_missing_start' else 'valid' end
  where run_id=v_run.run_id and player_id=v_player.player_id;
  select act1_timing_validity,case when act1_action_started_at is null then null else round(extract(epoch from (act1_locked_at-act1_action_started_at))*1000)::bigint end
  into v_validity,v_duration_ms from public.s3b_player_progress where run_id=v_run.run_id and player_id=v_player.player_id;
  perform public.s3b_log_formal_event(v_run.run_id,'act1_choice_locked',v_player.player_id,'player',jsonb_build_object('choice_id',p_choice_id,'response_duration_ms',v_duration_ms),v_validity,true);
  return v_result;
end;$$;

create or replace function public.s3b_complete_act1(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_complete_act1_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'act1_consequence_completed',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_submit_first_meeting(p_room_code text,p_session_token text,p_choice_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;v_validity text;v_duration_ms bigint;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_submit_first_meeting_pre014(p_room_code,p_session_token,p_choice_id);
  update public.s3b_player_progress set first_meeting_timing_validity=case when first_meeting_started_at is null then 'legacy_missing_start' else 'valid' end
  where run_id=v_run.run_id and player_id=v_player.player_id;
  select first_meeting_timing_validity,case when first_meeting_started_at is null then null else round(extract(epoch from (first_meeting_locked_at-first_meeting_started_at))*1000)::bigint end
  into v_validity,v_duration_ms from public.s3b_player_progress where run_id=v_run.run_id and player_id=v_player.player_id;
  perform public.s3b_log_formal_event(v_run.run_id,'first_meeting_choice_locked',v_player.player_id,'player',jsonb_build_object('choice_id',p_choice_id,'response_duration_ms',v_duration_ms),v_validity,true);
  return v_result;
end;$$;

create or replace function public.s3b_grab(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_grab_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'grab_completed',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_leave_start_room(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_leave_start_room_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'start_room_left',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_ack_route_update(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_ack_route_update_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'route_update_acknowledged',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_complete_foldback(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_complete_foldback_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'route_foldback_completed',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_follow_sign(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_follow_sign_pre014(p_room_code,p_session_token);
  perform public.s3b_log_formal_event(v_run.run_id,'follow_sign_completed',v_player.player_id,'player','{}','valid',false);
  return v_result;
end;$$;

create or replace function public.s3b_submit_act4_choice(p_room_code text,p_session_token text,p_choice_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_room text:=upper(trim(p_room_code));v_player public.s1_room_players%rowtype;v_run public.game_runs%rowtype;v_result jsonb;v_validity text;v_duration_ms bigint;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);v_run:=public.s2_get_active_run(v_room);
  v_result:=public.s3b_submit_act4_choice_pre014(p_room_code,p_session_token,p_choice_id);
  update public.s3b_player_progress set act4_timing_validity=case when act4_choice_started_at is null then 'legacy_missing_start' else 'valid' end
  where run_id=v_run.run_id and player_id=v_player.player_id;
  select act4_timing_validity,case when act4_choice_started_at is null then null else round(extract(epoch from (act4_locked_at-act4_choice_started_at))*1000)::bigint end
  into v_validity,v_duration_ms from public.s3b_player_progress where run_id=v_run.run_id and player_id=v_player.player_id;
  perform public.s3b_log_formal_event(v_run.run_id,'act4_choice_locked',v_player.player_id,'player',jsonb_build_object('choice_id',p_choice_id,'response_duration_ms',v_duration_ms),v_validity,true);
  return v_result;
end;$$;

-- Refresh first, then validate the resulting locked prefix while holding the
-- same run-state lock. Request identity makes uncertain retries idempotent.
create or replace function public.s3b_submit_library_code(
  p_room_code text,p_session_token text,p_client_request_id uuid,p_code text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_room text:=upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_run public.game_runs%rowtype;
  v_state public.s3b_run_state%rowtype;
  v_existing public.s3b_library_attempts%rowtype;
  v_n integer;
  v_hint integer;
  v_correct boolean;
begin
  if p_client_request_id is null then raise exception 'Puzzle request identity is required.'; end if;
  if p_code is null or p_code !~ '^[0-9]{5}$' then raise exception 'Library code must contain exactly five digits.'; end if;
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);
  select * into v_run from public.game_runs where room_code=v_room and status='active' for update;
  if not found then raise exception 'No active formal run.'; end if;

  select * into v_existing from public.s3b_library_attempts
  where run_id=v_run.run_id and submitted_by=v_player.player_id
    and client_request_id=p_client_request_id;
  if found then
    if v_existing.submitted_value<>p_code then
      raise exception 'Puzzle request identity was reused with a different code.';
    end if;
    return jsonb_build_object(
      'ok',true,'correct',v_existing.correct,'attempt_number',v_existing.attempt_number,
      'client_request_id',p_client_request_id,'idempotent_replay',true
    );
  end if;

  if not exists(select 1 from public.s3_runtime_scene_state
    where run_id=v_run.run_id and scene_id='act3_library' and phase_key='library_box') then
    raise exception 'Library Box transition is unavailable.';
  end if;
  perform public.s3b_refresh_puzzle(v_run.run_id);
  select * into v_state from public.s3b_run_state where run_id=v_run.run_id for update;
  if not found or not v_state.party_physically_reunited or v_state.puzzle_resolved_at is not null then
    raise exception 'Library Box is not accepting attempts.';
  end if;
  if left(p_code,length(v_state.puzzle_locked_prefix))<>v_state.puzzle_locked_prefix then
    raise exception 'Locked puzzle wheels cannot be changed.';
  end if;

  v_correct:=p_code='41739';
  update public.s3b_run_state
  set puzzle_attempt_number=puzzle_attempt_number+1,
      puzzle_hint_stage=case when v_correct then puzzle_hint_stage else greatest(puzzle_hint_stage,least(puzzle_attempt_number+1,3)) end,
      puzzle_resolved_at=case when v_correct then now() else null end,
      updated_at=now()
  where run_id=v_run.run_id
  returning puzzle_attempt_number,puzzle_hint_stage into v_n,v_hint;

  insert into public.s3b_library_attempts(
    run_id,attempt_number,submitted_by,submitted_value,submitted_at,correct,client_request_id
  ) values(v_run.run_id,v_n,v_player.player_id,p_code,now(),v_correct,p_client_request_id);
  perform public.s3b_log_formal_event(
    v_run.run_id,'library_code_submitted',v_player.player_id,'player',
    jsonb_build_object('attempt_number',v_n,'correct',v_correct,'hint_stage',v_hint),
    'valid',false,null,p_client_request_id
  );

  if v_correct then
    insert into public.s3_group_items(run_id,item_key,label_text_key)
    values(v_run.run_id,'library_photo_1897','item.photo_1897'),
          (v_run.run_id,'library_torn_note','item.torn_note')
    on conflict do nothing;
    perform public.s3b_set_scene(v_run.run_id,'act4_known_unknown','private_route_choice','initial','ACTION_SCREEN','act04-05.002');
  else
    perform public.s2_log_event(
      v_run.run_id,v_room,null,'puzzle_hint_used',v_player.player_id,
      jsonb_build_object('attempt_number',v_n,'hint_stage',v_hint,'behavior_scoring',false,'client_request_id',p_client_request_id)
    );
  end if;
  return jsonb_build_object(
    'ok',true,'correct',v_correct,'attempt_number',v_n,'hint_stage',v_hint,
    'client_request_id',p_client_request_id,'idempotent_replay',false
  );
end;
$$;

-- Canonical three-player Game-only Step Vote for ACT5 post-inspection route.
create or replace function public.s3b_submit_post_inspection_route_vote(
  p_room_code text,p_session_token text,p_choice_id text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_room text:=upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_run public.game_runs%rowtype;
  v_existing public.s3b_post_inspection_route_votes%rowtype;
  v_count integer;
  v_route text;
begin
  if p_choice_id not in ('known','unknown') then raise exception 'Post-inspection vote must be known or unknown.'; end if;
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);
  select * into v_run from public.game_runs where room_code=v_room and status='active' for update;
  if not found then raise exception 'No active formal run.'; end if;
  perform 1 from public.s3b_run_state where run_id=v_run.run_id for update;

  select * into v_existing from public.s3b_post_inspection_route_votes
  where run_id=v_run.run_id and player_id=v_player.player_id;
  if found then
    if v_existing.choice_id<>p_choice_id then
      raise exception 'Post-inspection vote is already locked.';
    end if;
    select count(*) into v_count from public.s3b_post_inspection_route_votes where run_id=v_run.run_id;
    select group_route into v_route from public.s3b_run_state where run_id=v_run.run_id;
    return jsonb_build_object('ok',true,'submitted_count',v_count,'resolved',v_route is not null,'group_route',v_route,'idempotent_replay',true);
  end if;

  if not exists(select 1 from public.s3_runtime_scene_state
    where run_id=v_run.run_id and scene_id='act5_inspect_first' and phase_key='post_inspection_route')
    or not exists(select 1 from public.s3b_run_state
      where run_id=v_run.run_id and pending_post_inspection_route and group_route is null) then
    raise exception 'Post-inspection vote is unavailable.';
  end if;

  insert into public.s3b_post_inspection_route_votes(run_id,player_id,choice_id)
  values(v_run.run_id,v_player.player_id,p_choice_id);
  perform public.s3b_log_formal_event(
    v_run.run_id,'post_inspection_route_vote_locked',v_player.player_id,'player',
    jsonb_build_object('decision_type','game_only_step_vote'),
    'valid',false
  );
  select count(*) into v_count from public.s3b_post_inspection_route_votes where run_id=v_run.run_id;

  if v_count=3 then
    select choice_id into v_route
    from public.s3b_post_inspection_route_votes
    where run_id=v_run.run_id
    group by choice_id order by count(*) desc,choice_id limit 1;
    update public.s3b_run_state
    set group_route=v_route,pending_post_inspection_route=false,
        terminal_state='SPRINT3B_COMPLETE',updated_at=now()
    where run_id=v_run.run_id and pending_post_inspection_route and group_route is null;
    if not found then raise exception 'Post-inspection route was resolved concurrently.'; end if;
    perform public.s3b_log_formal_event(
      v_run.run_id,'post_inspection_route_resolved',null,'server',
      jsonb_build_object('group_route',v_route,'resolution_source','three_player_majority','submitted_count',3),
      'valid',false
    );
    perform public.s3b_set_scene(
      v_run.run_id,'act5_route_resolved','terminal',v_route,'CINEMATIC_MESSAGE',
      case v_route when 'known' then 'act04-05.019' else 'act04-05.024' end
    );
  end if;
  return jsonb_build_object('ok',true,'submitted_count',v_count,'resolved',v_count=3,'group_route',v_route,'idempotent_replay',false);
end;
$$;

-- SHARE PHOTO requires an authoritative allowed scene and an open canonical
-- discussion. Ownership/current-view/provenance checks remain unchanged.
create or replace function public.s3_share_photo(
  p_room_code text,p_session_token text,p_recipient_role text,
  p_source_item_key text,p_source_view text
) returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_room text:=upper(trim(p_room_code));
  v_sender public.s1_room_players%rowtype;
  v_recipient uuid;
  v_run public.game_runs%rowtype;
  v_scene public.s3_runtime_scene_state%rowtype;
  v_label text;
  v_current text;
  v_copy uuid;
begin
  v_sender:=public.s1_get_player_by_session(v_room,p_session_token);
  v_run:=public.s2_get_active_run(v_room);
  if v_run.run_id is null then raise exception 'No active formal run.'; end if;
  select * into v_scene from public.s3_runtime_scene_state where run_id=v_run.run_id for update;
  if not found or not v_scene.allow_share_photo then raise exception 'Photo sharing is unavailable in the current scene.'; end if;
  if not exists(select 1 from public.discussion_sessions
    where run_id=v_run.run_id and scene_id=v_scene.scene_id and status='discussion') then
    raise exception 'Photo sharing requires an open canonical discussion.';
  end if;
  if not exists(select 1 from public.s3_player_items
    where run_id=v_run.run_id and item_key=p_source_item_key and physical_owner_id=v_sender.player_id) then
    raise exception 'Sender is not the physical owner of this item.';
  end if;
  select current_view into v_current from public.s3_player_item_view_state
  where run_id=v_run.run_id and player_id=v_sender.player_id and item_key=p_source_item_key;
  if v_current is null then raise exception 'Item view state is not initialized.'; end if;
  if p_source_view<>v_current then raise exception 'Only the current server-authoritative item view can be shared.'; end if;
  select name_text_key into v_label from public.s3_item_catalog
  where item_key=p_source_item_key and shareable_views ? v_current;
  if v_label is null then raise exception 'Current item view is not shareable.'; end if;
  select player_id into v_recipient from public.s1_room_players
  where room_code=v_room and role_slot=upper(trim(p_recipient_role));
  if v_recipient is null or v_recipient=v_sender.player_id then raise exception 'Invalid photo recipient.'; end if;
  insert into public.s3_shared_photos(
    run_id,received_by,shared_by,source_item_key,source_view,label_text_key
  ) values(v_run.run_id,v_recipient,v_sender.player_id,p_source_item_key,v_current,v_label)
  on conflict(run_id,received_by,shared_by,source_item_key,source_view)
  do update set shared_at=public.s3_shared_photos.shared_at
  returning photo_copy_id into v_copy;
  perform public.s3b_log_formal_event(
    v_run.run_id,'photo_shared',v_sender.player_id,'player',
    jsonb_build_object('photo_copy_id',v_copy,'received_by',v_recipient,'source_item_key',p_source_item_key,'source_view',v_current),
    'valid',true
  );
  return jsonb_build_object('ok',true,'photo_copy_id',v_copy,'source_view',v_current);
end;
$$;

-- Return reconnectable timing and private Game-only vote state without
-- revealing other players' votes before the server resolves the route.
alter function public.s3b_get_player_state(text,text) rename to s3b_get_player_state_pre014;
revoke execute on function public.s3b_get_player_state_pre014(text,text)
  from public,anon,authenticated;

create or replace function public.s3b_get_player_state(p_room_code text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_room text:=upper(trim(p_room_code));
  v_player public.s1_room_players%rowtype;
  v_run public.game_runs%rowtype;
  v_base jsonb;
  v_my_vote jsonb;
  v_count integer:=0;
  v_revealed jsonb:='[]'::jsonb;
  v_route text;
begin
  v_player:=public.s1_get_player_by_session(v_room,p_session_token);
  v_run:=public.s2_get_active_run(v_room);
  v_base:=public.s3b_get_player_state_pre014(p_room_code,p_session_token);
  if v_run.run_id is null then return v_base; end if;
  select jsonb_build_object('choice_id',choice_id,'locked_at',locked_at)
  into v_my_vote from public.s3b_post_inspection_route_votes
  where run_id=v_run.run_id and player_id=v_player.player_id;
  select count(*) into v_count from public.s3b_post_inspection_route_votes where run_id=v_run.run_id;
  select group_route into v_route from public.s3b_run_state where run_id=v_run.run_id;
  if v_route is not null then
    select coalesce(jsonb_agg(jsonb_build_object(
      'role_slot',p.role_slot,'choice_id',v.choice_id,'locked_at',v.locked_at
    ) order by p.role_slot),'[]'::jsonb) into v_revealed
    from public.s3b_post_inspection_route_votes v
    join public.s1_room_players p on p.player_id=v.player_id
    where v.run_id=v_run.run_id;
  end if;
  return v_base || jsonb_build_object(
    'post_inspection_vote_count',v_count,
    'my_post_inspection_vote',v_my_vote,
    'post_inspection_votes_revealed',v_revealed
  );
end;
$$;

-- Teacher event output exposes the explicit append-only ledger fields.
alter function public.s2_get_teacher_state(text,text) rename to s2_get_teacher_state_pre014;
revoke execute on function public.s2_get_teacher_state_pre014(text,text)
  from public,anon,authenticated;

create or replace function public.s2_get_teacher_state(p_room_code text,p_teacher_token text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  v_room text:=upper(trim(p_room_code));
  v_run public.game_runs%rowtype;
  v_base jsonb;
  v_events jsonb:='[]'::jsonb;
begin
  perform public.s1_assert_teacher(v_room,p_teacher_token);
  v_base:=public.s2_get_teacher_state_pre014(p_room_code,p_teacher_token);
  v_run:=public.s2_get_active_run(v_room);
  if v_run.run_id is not null then
    select coalesce(jsonb_agg(jsonb_build_object(
      'event_id',event_id,'event_type',event_type,
      'discussion_session_id',discussion_session_id,'scene_id',scene_id,
      'phase_key',phase_key,'step_key',step_key,'actor_player_id',actor_player_id,
      'event_source',event_source,'validity',validity,
      'behavior_scoring',behavior_scoring,'interaction_id',interaction_id,
      'client_request_id',client_request_id,'details',details,'created_at',created_at
    ) order by created_at,event_id),'[]'::jsonb)
    into v_events from public.runtime_events where run_id=v_run.run_id;
  end if;
  return jsonb_set(v_base,'{events}',v_events,true);
end;
$$;

-- Superseded public signatures and one-player route authority are closed.
revoke execute on function public.s3b_submit_library_code(text,text,text)
  from public,anon,authenticated;
revoke execute on function public.s3b_choose_post_inspection_route(text,text,text)
  from public,anon,authenticated;

grant execute on function public.s3b_ack_act1_opening(text,text),
  public.s3b_submit_act1_choice(text,text,text),
  public.s3b_complete_act1(text,text),
  public.s3b_submit_first_meeting(text,text,text),
  public.s3b_grab(text,text),
  public.s3b_leave_start_room(text,text),
  public.s3b_ack_route_update(text,text),
  public.s3b_complete_foldback(text,text),
  public.s3b_follow_sign(text,text),
  public.s3b_submit_act4_choice(text,text,text),
  public.s3b_submit_library_code(text,text,uuid,text),
  public.s3b_submit_post_inspection_route_vote(text,text,text),
  public.s3b_get_player_state(text,text),
  public.s3_share_photo(text,text,text,text,text),
  public.s2_get_teacher_state(text,text)
to anon,authenticated;
