-- Sprint 5 focused re-audit corrections: evidence access, exact teacher state, and replay-first votes.
create or replace function public.s5_configure_discussion(p_session uuid,p_phase text)
returns void language plpgsql security definer set search_path=public as $$
declare secs int;options jsonb;policy text;maxr int;fallback text;
begin
 secs:=case p_phase when'act6_vote'then 90 when'act8_final_vote'then 180 else 15 end;
 options:=case p_phase when'act6_vote'then'[{"id":"escape","label":"act06.002"},{"id":"1897","label":"act06.003"},{"id":"time_stopped","label":"act06.004"},{"id":"trapped","label":"act06.005"}]'::jsonb when'act7_vote'then'[{"id":"clock_a","label":"act07.008"},{"id":"clock_b","label":"act07.009"},{"id":"clock_c","label":"act07.010"}]'::jsonb else'[{"id":"main_gate","label":"act08.001"},{"id":"west_tower","label":"act08.002"}]'::jsonb end;
 policy:=case p_phase when'act6_vote'then'SINGLE_REVOTE_THEN_FALLBACK'when'act7_vote'then'REPEAT_UNTIL_MAJORITY'else'NO_TIE_POSSIBLE'end;maxr:=case when p_phase='act6_vote'then 1 end;fallback:=case when p_phase='act6_vote'then'portrait_fixed_fallback'end;
 update public.discussion_sessions set phase_key=p_phase,status='discussion',started_at=now(),phase_deadline=now()+make_interval(secs=>secs),ended_at=null,outcome=null,show_initial_choices=p_phase='act8_final_vote',allow_free_text=true,allow_pocket=true,allow_memories_observations=true,allow_share_photo=p_phase in('act6_vote','act8_final_vote'),require_final_vote=true,vote_options=options,tie_policy=policy,revote_window_sec=15,max_revotes=maxr,fallback_resolution=fallback,discussion_time_limit_sec=secs,vote_time_limit_sec=60,silent_texting_mode=true where discussion_session_id=p_session;
 if not found then raise exception'Sprint 5 canonical discussion link is missing.';end if;
end$$;

alter function public.s5_initialize(text,text) rename to s5_initialize_pre031;
revoke execute on function public.s5_initialize_pre031(text,text) from public,anon,authenticated;
create function public.s5_initialize(p_room_code text,p_teacher_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;begin result:=public.s5_initialize_pre031(p_room_code,p_teacher_token);update public.s3_runtime_scene_state set allow_share_photo=true where run_id=(result->>'run_id')::uuid;return result;end$$;

alter function public.s5_advance(text,text) rename to s5_advance_pre031;
revoke execute on function public.s5_advance_pre031(text,text) from public,anon,authenticated;
create function public.s5_advance(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;g public.game_runs%rowtype;s public.s5_run_state%rowtype;begin result:=public.s5_advance_pre031(p_room_code,p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));select*into s from public.s5_run_state where run_id=g.run_id;update public.s3_runtime_scene_state set allow_share_photo=s.phase_key='act8_final_vote' where run_id=g.run_id;return result;end$$;

alter function public.s5_submit_vote(text,text,uuid,integer,uuid,text) rename to s5_submit_vote_pre031;
revoke execute on function public.s5_submit_vote_pre031(text,text,uuid,integer,uuid,text) from public,anon,authenticated;
create function public.s5_submit_vote(p_room_code text,p_session_token text,p_expected_discussion_session_id uuid,p_expected_vote_round int,p_client_request_id uuid,p_choice_id text)returns jsonb language plpgsql security definer set search_path=public as $$
declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;prior public.s5_votes%rowtype;
begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into prior from public.s5_votes where run_id=g.run_id and player_id=p.player_id and client_request_id=p_client_request_id;if found then if prior.choice_id<>p_choice_id then raise exception'Vote request identity was reused with different content.';end if;return jsonb_build_object('ok',true,'idempotent_replay',true,'choice_id',prior.choice_id);end if;return public.s5_submit_vote_pre031(p_room_code,p_session_token,p_expected_discussion_session_id,p_expected_vote_round,p_client_request_id,p_choice_id);end$$;

create function public.s5_get_teacher_discussion_state(p_room_code text,p_teacher_token text)returns jsonb language plpgsql security definer set search_path=public as $$
declare room text:=upper(trim(p_room_code));g public.game_runs%rowtype;s public.s5_run_state%rowtype;d public.discussion_sessions%rowtype;sid uuid;msgs jsonb:='[]';votes jsonb:='[]';
begin perform public.s1_assert_teacher(room,p_teacher_token);g:=public.s2_get_active_run(room);if g.run_id is null then return jsonb_build_object('active',false,'sprint5_active',false);end if;select*into s from public.s5_run_state where run_id=g.run_id;if not found then return jsonb_build_object('active',true,'sprint5_active',false);end if;
 select ds.* into d from public.discussion_sessions ds join public.s5_rounds r using(discussion_session_id)where r.run_id=g.run_id and r.phase_key=s.phase_key and r.vote_round=s.vote_round;if found then sid:=d.discussion_session_id;perform public.s2_refresh_discussion(sid);select*into d from public.discussion_sessions where discussion_session_id=sid;select coalesce(jsonb_agg(jsonb_build_object('display_name',rp.display_name,'role_slot',rp.role_slot,'message_text',m.message_text,'created_at',m.created_at)order by m.created_at),'[]')into msgs from public.dialogue_messages m join public.s1_room_players rp using(player_id)where m.discussion_session_id=sid;select coalesce(jsonb_agg(jsonb_build_object('display_name',rp.display_name,'role_slot',rp.role_slot,'submitted',v.player_id is not null,'choice_label',case when d.status='resolved'then v.choice_id end,'locked_at',v.locked_at)order by rp.role_slot),'[]')into votes from public.s1_room_players rp left join public.s5_votes v on v.player_id=rp.player_id and v.run_id=g.run_id and v.phase_key=s.phase_key and v.vote_round=s.vote_round where rp.room_code=room;end if;
 return jsonb_build_object('active',true,'sprint5_active',true,'canonical_flow_active',true,'run',jsonb_build_object('run_id',g.run_id,'run_mode',g.run_mode,'behavior_dataset_eligible',g.behavior_dataset_eligible),'discussion',case when d.discussion_session_id is null then null else jsonb_build_object('discussion_session_id',d.discussion_session_id,'topic',d.topic,'status',d.status,'vote_round',s.vote_round,'phase_deadline',d.phase_deadline,'outcome',d.outcome)end,'messages',msgs,'current_votes',votes,'teacher_override',jsonb_build_object('allowed_actions','[]'::jsonb,'history','[]'::jsonb));end$$;

create function public.s5_teacher_open_vote(p_room_code text,p_teacher_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));g public.game_runs%rowtype;s public.s5_run_state%rowtype;sid uuid;begin perform public.s1_assert_teacher(room,p_teacher_token);g:=public.s2_get_active_run(room);select*into s from public.s5_run_state where run_id=g.run_id;select discussion_session_id into sid from public.s5_rounds where run_id=g.run_id and phase_key=s.phase_key and vote_round=s.vote_round;update public.discussion_sessions set status='voting',phase_deadline=now()+make_interval(secs=>vote_time_limit_sec)where discussion_session_id=sid and status='discussion';if not found then raise exception'Current Sprint 5 discussion is not open.';end if;return jsonb_build_object('ok',true,'discussion_session_id',sid);end$$;
create function public.s5_teacher_add_time(p_room_code text,p_teacher_token text,p_seconds integer)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));g public.game_runs%rowtype;s public.s5_run_state%rowtype;sid uuid;begin if p_seconds<1 or p_seconds>600 then raise exception'Invalid time extension.';end if;perform public.s1_assert_teacher(room,p_teacher_token);g:=public.s2_get_active_run(room);select*into s from public.s5_run_state where run_id=g.run_id;select discussion_session_id into sid from public.s5_rounds where run_id=g.run_id and phase_key=s.phase_key and vote_round=s.vote_round;update public.discussion_sessions set phase_deadline=greatest(coalesce(phase_deadline,now()),now())+make_interval(secs=>p_seconds)where discussion_session_id=sid and status in('discussion','voting','waiting_for_missing_player');if not found then raise exception'Current Sprint 5 discussion cannot receive time.';end if;return jsonb_build_object('ok',true,'discussion_session_id',sid);end$$;

revoke execute on function public.s5_get_teacher_discussion_state(text,text),public.s5_teacher_open_vote(text,text),public.s5_teacher_add_time(text,text,integer) from public;
grant execute on function public.s5_initialize(text,text),public.s5_advance(text,text),public.s5_submit_vote(text,text,uuid,integer,uuid,text),public.s5_get_teacher_discussion_state(text,text),public.s5_teacher_open_vote(text,text),public.s5_teacher_add_time(text,text,integer) to anon,authenticated;
