-- Sprint 6 ACT 9-13 authoritative runtime. ACT 14/finalization is intentionally excluded.
begin;
create table public.s6_run_state(
 run_id uuid primary key references public.game_runs(run_id),act_no int not null default 9,
 phase_key text not null default 'act9_discussion',act9_step int not null default 1,round_no int not null default 1,
 red_activated boolean not null default false,blue_activated boolean not null default false,
 gold_key boolean,alarm_active boolean not null default false,station_c_bypassed boolean not null default false,
 danger_arrives_sooner boolean not null default false,allocation_valid boolean not null default false,
 mechanism_failure_station text check(mechanism_failure_station in('A','B','C')),
 mechanism_failure_active boolean not null default false,failure_resolution text,
 escape_success boolean not null default false,act14_boundary_reached boolean not null default false,
 updated_at timestamptz not null default now()
);
create table public.s6_private_clues(run_id uuid references public.game_runs(run_id),player_id uuid references public.s1_room_players(player_id),act_no int,knowledge_key text,text_key text,delivered_at timestamptz not null default now(),primary key(run_id,player_id,act_no));
create table public.s6_choices(run_id uuid references public.game_runs(run_id),phase_key text,round_no int,player_id uuid references public.s1_room_players(player_id),choice_id text,client_request_id uuid,response_latency_ms int,role_context text,locked_at timestamptz not null default now(),primary key(run_id,phase_key,round_no,player_id),unique(run_id,player_id,client_request_id));
create table public.s6_allocations(run_id uuid references public.game_runs(run_id),player_id uuid references public.s1_room_players(player_id),role_key text,client_request_id uuid,locked_at timestamptz not null default now(),primary key(run_id,player_id),unique(run_id,player_id,client_request_id));
create table public.s6_engagements(run_id uuid references public.game_runs(run_id),role_key text,player_id uuid references public.s1_room_players(player_id),engaged_at timestamptz not null default now(),primary key(run_id,role_key));
alter table public.s6_run_state enable row level security;alter table public.s6_private_clues enable row level security;alter table public.s6_choices enable row level security;alter table public.s6_allocations enable row level security;alter table public.s6_engagements enable row level security;
insert into public.s3_knowledge_catalog(knowledge_key)values('great_hall_red_first'),('great_hall_first_door_unsafe'),('great_hall_blue_after_red'),('golden_key_saves_time'),('golden_key_triggers_alarm_sooner'),('golden_key_not_required')on conflict do nothing;
insert into public.s3_item_catalog(item_key,name_text_key,shareable_views)values('golden_key','act10.006','[]')on conflict(item_key)do nothing;

create function public.s6_set_scene(p_run uuid,p_scene text,p_phase text,p_step text,p_mode text,p_text text)returns void language plpgsql security definer set search_path=public as $$begin perform public.s3b_set_scene(p_run,p_scene,p_phase,p_step,p_mode,p_text);end$$;
revoke execute on function public.s6_set_scene(uuid,text,text,text,text,text)from public,anon,authenticated;

create function public.s6_deliver_clues(p_run uuid,p_act int)returns void language plpgsql security definer set search_path=public as $$
declare x record;k text;t text;
begin for x in select player_id,role_slot from public.s1_room_players where room_code=(select room_code from public.game_runs where run_id=p_run)loop
 if p_act=9 then k:=case x.role_slot when'GAL-A'then'great_hall_red_first'when'GAL-B'then'great_hall_first_door_unsafe'else'great_hall_blue_after_red'end;t:=case x.role_slot when'GAL-A'then'act09.005'when'GAL-B'then'act09.006'else'act09.007'end;
 else k:=case x.role_slot when'GAL-A'then'golden_key_saves_time'when'GAL-B'then'golden_key_triggers_alarm_sooner'else'golden_key_not_required'end;t:=case x.role_slot when'GAL-A'then'act10.001'when'GAL-B'then'act10.002'else'act10.003'end;end if;
 insert into public.s6_private_clues values(p_run,x.player_id,p_act,k,t,now())on conflict do nothing;perform public.s3_record_knowledge(p_run,x.player_id,k,'private_system_message','ACT_'||p_act,null,null);end loop;end$$;
revoke execute on function public.s6_deliver_clues(uuid,int)from public,anon,authenticated;

create function public.s6_initialize(p_room_code text,p_teacher_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));g public.game_runs%rowtype;begin perform public.s1_assert_teacher(room,p_teacher_token);g:=public.s2_get_active_run(room);if not exists(select 1 from public.s5_run_state where run_id=g.run_id and phase_key='complete')then raise exception'Sprint 6 requires verified ACT 6-8 completion.';end if;insert into public.s6_run_state(run_id)values(g.run_id);perform public.s6_deliver_clues(g.run_id,9);perform public.s6_set_scene(g.run_id,'act9_great_hall','act9_discussion','private_clues','CINEMATIC_MESSAGE','act09.004');perform public.s2_log_event(g.run_id,room,null,'s6_initialized',null,jsonb_build_object('behavior_scoring',false));return jsonb_build_object('ok',true,'run_id',g.run_id);end$$;

create function public.s6_open_act9_console(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);update public.s6_run_state set phase_key='act9_console',updated_at=now()where run_id=g.run_id and phase_key='act9_discussion';perform public.s6_set_scene(g.run_id,'act9_great_hall','act9_console','step_1','ACTION_SCREEN','act09.010');return jsonb_build_object('ok',true);end$$;

create function public.s6_submit_group_choice(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text)returns jsonb language plpgsql security definer set search_path=public as $$
declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;prior public.s6_choices%rowtype;n int;d int;winner text;correct boolean;penalty boolean:=false;
begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;select*into prior from public.s6_choices where run_id=g.run_id and player_id=p.player_id and client_request_id=p_client_request_id;if found then if prior.choice_id<>p_choice_id then raise exception'Request identity reused with different content.';end if;return jsonb_build_object('ok',true,'idempotent_replay',true);end if;
 if s.phase_key not in('act9_console','act10_final_vote')then raise exception'No Sprint 6 group choice is open.';end if;insert into public.s6_choices values(g.run_id,s.phase_key,s.round_no,p.player_id,p_choice_id,p_client_request_id,null,null,now());select count(*),count(distinct choice_id)into n,d from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no;if n<3 then return jsonb_build_object('ok',true,'submitted',n);end if;
 if d=3 then update public.s6_run_state set round_no=round_no+1,updated_at=now()where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act9_great_hall','act9_console','no_consensus','CRITICAL_INFO','act09.009');return jsonb_build_object('ok',true,'no_consensus',true,'action_executed',false);end if;
 select choice_id into winner from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no group by choice_id order by count(*)desc,choice_id limit 1;
 if s.phase_key='act10_final_vote'then update public.s6_run_state set gold_key=winner='take',alarm_active=winner='take',station_c_bypassed=winner='take',danger_arrives_sooner=winner='take',phase_key='act10_result',updated_at=now()where run_id=g.run_id;if winner='take'then insert into public.s3_group_items(run_id,item_key,label_text_key)values(g.run_id,'golden_key','act10.006')on conflict do nothing;end if;return jsonb_build_object('ok',true,'resolved',true,'choice_id',winner);end if;
 correct:=case s.act9_step when 1 then winner='red'when 2 then winner='do_not_enter'when 3 then winner='blue'else winner='enter_blue'end;
 if s.act9_step=4 and winner='stay'then update public.s6_run_state set round_no=round_no+1 where run_id=g.run_id;return jsonb_build_object('ok',true,'stay',true,'penalty',false);end if;
 if not correct then penalty:=true;update public.s6_run_state set act9_step=case when act9_step=1 then 1 else 1 end,red_activated=false,blue_activated=false,round_no=round_no+1,updated_at=now()where run_id=g.run_id;perform public.s2_log_event(g.run_id,room,null,'escape_penalty_event',p.player_id,jsonb_build_object('penalty_key','great_hall_wrong_door','step',s.act9_step,'choice_id',winner,'behavior_scoring',false));return jsonb_build_object('ok',true,'soft_failure',true,'penalty',true);end if;
 if s.act9_step<4 then update public.s6_run_state set act9_step=act9_step+1,red_activated=true,blue_activated=s.act9_step>=3,round_no=round_no+1,updated_at=now()where run_id=g.run_id;else update public.s6_run_state set act_no=10,phase_key='act10_private',round_no=1,updated_at=now()where run_id=g.run_id;perform public.s6_deliver_clues(g.run_id,10);perform public.s6_set_scene(g.run_id,'act10_golden_key','act10_private','initial','ACTION_SCREEN','act10.004');end if;return jsonb_build_object('ok',true,'resolved',true,'choice_id',winner,'penalty',penalty);end$$;

create function public.s6_submit_private_choice(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;n int;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;if s.phase_key not in('act10_private','act12_pressure')then raise exception'No private Sprint 6 choice is open.';end if;insert into public.s6_choices values(g.run_id,s.phase_key,s.round_no,p.player_id,p_choice_id,p_client_request_id,extract(epoch from(now()-s.updated_at))*1000,(select role_key from public.s6_allocations where run_id=g.run_id and player_id=p.player_id),now())on conflict(run_id,player_id,client_request_id)do nothing;select count(*)into n from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no;if n=3 and s.phase_key='act10_private'then update public.s6_run_state set phase_key='act10_final_vote',round_no=1 where run_id=g.run_id;elsif n=3 then update public.s6_run_state set phase_key='act12_cinematic',failure_resolution='cinematic_auto_resolution',mechanism_failure_active=false,escape_success=true,act_no=13 where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act13_escape','act13_boundary','escape_success','CINEMATIC_MESSAGE','act13.001');end if;return jsonb_build_object('ok',true,'submitted',n);end$$;

create function public.s6_advance(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;if s.phase_key='act10_result'then update public.s6_run_state set act_no=11,phase_key='act11_allocation',round_no=1 where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act11_main_gate','act11_allocation','initial','ACTION_SCREEN','act11.001');elsif s.phase_key='act12_cinematic'and s.escape_success then update public.s6_run_state set phase_key='act13_boundary',act14_boundary_reached=true where run_id=g.run_id;else raise exception'No Sprint 6 transition is available.';end if;return jsonb_build_object('ok',true);end$$;

create function public.s6_submit_allocation(p_room_code text,p_session_token text,p_client_request_id uuid,p_role_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;n int;distinct_n int;c_owner text;valid boolean;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;if s.phase_key<>'act11_allocation'then raise exception'Allocation is not open.';end if;insert into public.s6_allocations values(g.run_id,p.player_id,p_role_key,p_client_request_id,now())on conflict(run_id,player_id)do update set role_key=excluded.role_key,client_request_id=excluded.client_request_id,locked_at=now();select count(*),count(distinct role_key)into n,distinct_n from public.s6_allocations where run_id=g.run_id;if n<3 then return jsonb_build_object('ok',true,'submitted',n);end if;select rp.role_slot into c_owner from public.s6_allocations a join public.s1_room_players rp using(player_id)where a.run_id=g.run_id and a.role_key='C';valid:=distinct_n=3 and((s.gold_key and not exists(select 1 from public.s6_allocations where run_id=g.run_id and role_key not in('A','B','WATCHER')))or(not s.gold_key and not exists(select 1 from public.s6_allocations where run_id=g.run_id and role_key not in('A','B','C'))and c_owner='GAL-C'));if not valid then delete from public.s6_allocations where run_id=g.run_id;update public.s6_run_state set round_no=round_no+1 where run_id=g.run_id;perform public.s2_log_event(g.run_id,room,null,'escape_penalty_event',null,jsonb_build_object('penalty_key','allocation_rework','behavior_scoring',false));return jsonb_build_object('ok',true,'allocation_valid',false,'wrong_c_owner',c_owner is not null and c_owner<>'GAL-C');end if;update public.s6_run_state set allocation_valid=true,act_no=12,phase_key='act12_engage',round_no=1 where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act12_main_gate','act12_engage','waiting','ACTION_SCREEN','act11.001');return jsonb_build_object('ok',true,'allocation_valid',true);end$$;

create function public.s6_engage(p_room_code text,p_session_token text,p_role_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;n int;needed int;failure text;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;if s.phase_key<>'act12_engage'or not exists(select 1 from public.s6_allocations where run_id=g.run_id and player_id=p.player_id and role_key=p_role_key)then raise exception'Role ENGAGE is invalid.';end if;insert into public.s6_engagements values(g.run_id,p_role_key,p.player_id,now())on conflict do nothing;select count(*)into n from public.s6_engagements where run_id=g.run_id;needed:=3;if n=needed and not s.mechanism_failure_active then select role_key into failure from public.s6_allocations where run_id=g.run_id and role_key in('A','B','C')order by md5(g.run_id::text||role_key)limit 1;update public.s6_run_state set phase_key='act12_pressure',mechanism_failure_active=true,mechanism_failure_station=failure,failure_resolution='pending',round_no=1,updated_at=now()where run_id=g.run_id;end if;return jsonb_build_object('ok',true,'engaged',n,'failure_started',n=needed,'failure_station',case when n=needed then failure end);end$$;

create function public.s6_get_player_state(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id;if not found then return jsonb_build_object('active',false);end if;return jsonb_build_object('active',true,'state',to_jsonb(s),'private_clue',(select jsonb_build_object('knowledge_key',knowledge_key,'text_key',text_key)from public.s6_private_clues where run_id=g.run_id and player_id=p.player_id and act_no=s.act_no),'allocation',(select role_key from public.s6_allocations where run_id=g.run_id and player_id=p.player_id),'engaged_roles',(select coalesce(jsonb_agg(role_key),'[]')from public.s6_engagements where run_id=g.run_id),'game_completed',false,'export_ready',false);end$$;

revoke execute on function public.s6_initialize(text,text),public.s6_open_act9_console(text,text),public.s6_submit_group_choice(text,text,uuid,text),public.s6_submit_private_choice(text,text,uuid,text),public.s6_advance(text,text),public.s6_submit_allocation(text,text,uuid,text),public.s6_engage(text,text,text),public.s6_get_player_state(text,text)from public;
grant execute on function public.s6_initialize(text,text),public.s6_open_act9_console(text,text),public.s6_submit_group_choice(text,text,uuid,text),public.s6_submit_private_choice(text,text,uuid,text),public.s6_advance(text,text),public.s6_submit_allocation(text,text,uuid,text),public.s6_engage(text,text,text),public.s6_get_player_state(text,text)to anon,authenticated;
commit;
