-- Sprint 6 contract hardening after deployed migration 033.
begin;

create or replace function public.s6_submit_group_choice(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text)returns jsonb language plpgsql security definer set search_path=public as $$
declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;prior public.s6_choices%rowtype;n int;d int;winner text;correct boolean;feedback text;
begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;select*into prior from public.s6_choices where run_id=g.run_id and player_id=p.player_id and client_request_id=p_client_request_id;if found then if prior.choice_id<>p_choice_id then raise exception'Request identity reused with different content.';end if;return jsonb_build_object('ok',true,'idempotent_replay',true);end if;
 if s.phase_key not in('act9_console','act10_final_vote')then raise exception'No Sprint 6 group choice is open.';end if;
 if s.phase_key='act10_final_vote'and p_choice_id not in('take','leave')then raise exception'Invalid ACT 10 choice.';end if;
 if s.phase_key='act9_console'and not(case when s.act9_step in(1,3)then p_choice_id in('red','blue','black')when s.act9_step=2 then p_choice_id in('enter_red','do_not_enter')when s.act9_step=4 then p_choice_id in('enter_blue','stay')else false end)then raise exception'Invalid Great Hall choice for current step.';end if;
 insert into public.s6_choices values(g.run_id,s.phase_key,s.round_no,p.player_id,p_choice_id,p_client_request_id,null,null,now());select count(*),count(distinct choice_id)into n,d from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no;if n<3 then return jsonb_build_object('ok',true,'submitted',n);end if;
 if d=3 then update public.s6_run_state set round_no=round_no+1,updated_at=now()where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act9_great_hall','act9_console','no_consensus','CRITICAL_INFO','act09.009');return jsonb_build_object('ok',true,'no_consensus',true,'action_executed',false,'feedback_text_key','act09.009');end if;
 select choice_id into winner from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no group by choice_id order by count(*)desc,choice_id limit 1;
 if s.phase_key='act10_final_vote'then update public.s6_run_state set gold_key=winner='take',alarm_active=winner='take',station_c_bypassed=winner='take',danger_arrives_sooner=winner='take',phase_key='act10_result',updated_at=now()where run_id=g.run_id;if winner='take'then insert into public.s3_group_items(run_id,item_key,label_text_key)values(g.run_id,'golden_key','act10.006')on conflict do nothing;end if;return jsonb_build_object('ok',true,'resolved',true,'choice_id',winner);end if;
 correct:=case s.act9_step when 1 then winner='red'when 2 then winner='do_not_enter'when 3 then winner='blue'else winner='enter_blue'end;
 if s.act9_step=4 and winner='stay'then update public.s6_run_state set round_no=round_no+1,updated_at=now()where run_id=g.run_id;return jsonb_build_object('ok',true,'stay',true,'penalty',false,'action_executed',false,'feedback_text_key','act09.021');end if;
 if not correct then feedback:=case s.act9_step when 1 then'act09.012'when 2 then'act09.017'when 3 then'act09.019'else'act09.023'end;update public.s6_run_state set act9_step=1,red_activated=false,blue_activated=false,round_no=round_no+1,updated_at=now()where run_id=g.run_id;perform public.s2_log_event(g.run_id,room,null,'escape_penalty_event',p.player_id,jsonb_build_object('penalty_key','great_hall_wrong_door','step',s.act9_step,'choice_id',winner,'feedback_text_key',feedback,'behavior_scoring',false));return jsonb_build_object('ok',true,'soft_failure',true,'penalty',true,'feedback_text_key',feedback);end if;
 if s.act9_step<4 then update public.s6_run_state set act9_step=act9_step+1,red_activated=true,blue_activated=s.act9_step>=3,round_no=round_no+1,updated_at=now()where run_id=g.run_id;else update public.s6_run_state set act_no=10,phase_key='act10_private',round_no=1,updated_at=now()where run_id=g.run_id;perform public.s6_deliver_clues(g.run_id,10);perform public.s6_set_scene(g.run_id,'act10_golden_key','act10_private','initial','ACTION_SCREEN','act10.004');end if;return jsonb_build_object('ok',true,'resolved',true,'choice_id',winner,'penalty',false);end$$;

create or replace function public.s6_submit_private_choice(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;n int;role text;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;role:=(select role_key from public.s6_allocations where run_id=g.run_id and player_id=p.player_id);if s.phase_key not in('act10_private','act12_pressure')then raise exception'No private Sprint 6 choice is open.';end if;if s.phase_key='act10_private'and p_choice_id not in('take','leave')then raise exception'Invalid ACT 10 private choice.';end if;if s.phase_key='act12_pressure'and((role=s.mechanism_failure_station and p_choice_id not in('one','two','three','four'))or(role<>s.mechanism_failure_station and p_choice_id not in('hold','encourage','watch','prepare')))then raise exception'Invalid pressure choice for role context.';end if;
 insert into public.s6_choices values(g.run_id,s.phase_key,s.round_no,p.player_id,p_choice_id,p_client_request_id,round(extract(epoch from(now()-s.updated_at))*1000)::int,role,now())on conflict(run_id,player_id,client_request_id)do nothing;select count(*)into n from public.s6_choices where run_id=g.run_id and phase_key=s.phase_key and round_no=s.round_no;if n=3 and s.phase_key='act10_private'then update public.s6_run_state set phase_key='act10_final_vote',round_no=1,updated_at=now()where run_id=g.run_id;elsif n=3 then update public.s6_run_state set phase_key='act12_cinematic',failure_resolution='cinematic_auto_resolution',mechanism_failure_active=false,escape_success=true,act_no=13,updated_at=now()where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act13_escape','act13_boundary','escape_success','CINEMATIC_MESSAGE','act13.001');end if;return jsonb_build_object('ok',true,'submitted',n);end$$;

create or replace function public.s6_submit_allocation(p_room_code text,p_session_token text,p_client_request_id uuid,p_role_key text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;n int;distinct_n int;c_owner text;valid boolean;prior public.s6_allocations%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id for update;if s.phase_key<>'act11_allocation'then raise exception'Allocation is not open.';end if;if(s.gold_key and p_role_key not in('A','B','WATCHER'))or(not s.gold_key and p_role_key not in('A','B','C'))then raise exception'Invalid role for Golden Key branch.';end if;select*into prior from public.s6_allocations where run_id=g.run_id and player_id=p.player_id and client_request_id=p_client_request_id;if found then if prior.role_key<>p_role_key then raise exception'Request identity reused with different content.';end if;return jsonb_build_object('ok',true,'idempotent_replay',true);end if;
 insert into public.s6_allocations values(g.run_id,p.player_id,p_role_key,p_client_request_id,now())on conflict(run_id,player_id)do update set role_key=excluded.role_key,client_request_id=excluded.client_request_id,locked_at=now();select count(*),count(distinct role_key)into n,distinct_n from public.s6_allocations where run_id=g.run_id;if n<3 then return jsonb_build_object('ok',true,'submitted',n);end if;select rp.role_slot into c_owner from public.s6_allocations a join public.s1_room_players rp using(player_id)where a.run_id=g.run_id and a.role_key='C';valid:=distinct_n=3 and((s.gold_key and not exists(select 1 from public.s6_allocations where run_id=g.run_id and role_key not in('A','B','WATCHER')))or(not s.gold_key and not exists(select 1 from public.s6_allocations where run_id=g.run_id and role_key not in('A','B','C'))and c_owner='GAL-C'));if not valid then delete from public.s6_allocations where run_id=g.run_id;update public.s6_run_state set round_no=round_no+1,updated_at=now()where run_id=g.run_id;perform public.s2_log_event(g.run_id,room,null,'escape_penalty_event',null,jsonb_build_object('penalty_key','allocation_rework','behavior_scoring',false));return jsonb_build_object('ok',true,'allocation_valid',false,'wrong_c_owner',c_owner is not null and c_owner<>'GAL-C');end if;update public.s6_run_state set allocation_valid=true,act_no=12,phase_key='act12_engage',round_no=1,updated_at=now()where run_id=g.run_id;perform public.s6_set_scene(g.run_id,'act12_main_gate','act12_engage','waiting','ACTION_SCREEN','act11.001');return jsonb_build_object('ok',true,'allocation_valid',true);end$$;

create or replace function public.s6_get_player_state(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);select*into s from public.s6_run_state where run_id=g.run_id;if not found then return jsonb_build_object('active',false);end if;return jsonb_build_object('active',true,'state',to_jsonb(s),'role_slot',p.role_slot,'private_clue',(select jsonb_build_object('knowledge_key',knowledge_key,'text_key',text_key)from public.s6_private_clues where run_id=g.run_id and player_id=p.player_id and act_no=s.act_no),'private_choices_revealed',case when s.act_no>10 or s.phase_key in('act10_final_vote','act10_result')then(select coalesce(jsonb_agg(jsonb_build_object('role_slot',rp.role_slot,'choice_id',c.choice_id)order by rp.role_slot),'[]')from public.s6_choices c join public.s1_room_players rp using(player_id)where c.run_id=g.run_id and c.phase_key='act10_private')else'[]'::jsonb end,'allocation',(select role_key from public.s6_allocations where run_id=g.run_id and player_id=p.player_id),'engaged_roles',(select coalesce(jsonb_agg(role_key),'[]')from public.s6_engagements where run_id=g.run_id),'game_completed',false,'export_ready',false);end$$;

commit;
