begin;

create table public.s6_station_b_progress(
 run_id uuid primary key references public.game_runs(run_id) on delete cascade,
 player_id uuid not null references public.s1_room_players(player_id),
 stage text not null check(stage in('lever_held','indicator_center')),
 held_at timestamptz not null default now(),
 centered_at timestamptz
);

create function public.s6_request_lock(p_run uuid,p_player uuid,p_request uuid)returns void language sql as $$select pg_advisory_xact_lock(hashtextextended(p_run::text||':'||p_player::text||':'||p_request::text,0))$$;
revoke execute on function public.s6_request_lock(uuid,uuid,uuid)from public,anon,authenticated;

create function public.s6_send_message_v2(p_room_code text,p_session_token text,p_expected_discussion_session_id uuid,p_client_request_id uuid,p_message_text text)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);return public.s6_send_message_guarded(p_room_code,p_session_token,p_expected_discussion_session_id,p_client_request_id,p_message_text);end$$;

create function public.s6_close_discussion_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_expected_phase text,p_expected_step int,p_expected_round int,p_expected_discussion_session_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;prior public.s6_action_receipts%rowtype;result jsonb;payload jsonb:=jsonb_build_object('phase',p_expected_phase,'step',p_expected_step,'round',p_expected_round,'session',p_expected_discussion_session_id);begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);select*into prior from public.s6_action_receipts where run_id=g.run_id and player_id=p.player_id and request_id=p_client_request_id;if found then if prior.action_key<>'discussion_close'or prior.payload<>payload then raise exception'Request identity reused with different content.';end if;return prior.result||jsonb_build_object('idempotent_replay',true);end if;result:=public.s6_close_discussion_guarded(p_room_code,p_session_token,p_expected_phase,p_expected_step,p_expected_round,p_expected_discussion_session_id);insert into public.s6_action_receipts values(g.run_id,p.player_id,p_client_request_id,'discussion_close',payload,result,now());return result;end$$;

create function public.s6_submit_group_choice_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);return public.s6_submit_group_choice_guarded(p_room_code,p_session_token,p_client_request_id,p_choice_id,p_expected_phase,p_expected_step,p_expected_round);end$$;
create function public.s6_submit_private_choice_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_choice_id text,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);return public.s6_submit_private_choice_guarded(p_room_code,p_session_token,p_client_request_id,p_choice_id,p_expected_phase,p_expected_step,p_expected_round);end$$;
create function public.s6_submit_allocation_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_role_key text,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);return public.s6_submit_allocation_guarded(p_room_code,p_session_token,p_client_request_id,p_role_key,p_expected_phase,p_expected_step,p_expected_round);end$$;
create function public.s6_engage_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_role_key text,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);return public.s6_engage_guarded(p_room_code,p_session_token,p_client_request_id,p_role_key,p_expected_phase,p_expected_step,p_expected_round);end$$;

create function public.s6_advance_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;result jsonb;begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);select*into s from public.s6_run_state where run_id=g.run_id;if p_expected_phase='act13_escape'and s.stage_started_at+interval'3 seconds'>now()then raise exception'Signal restoration pause is still active.';end if;result:=public.s6_advance_guarded(p_room_code,p_session_token,p_client_request_id,p_expected_phase,p_expected_step,p_expected_round);if p_expected_phase='act10_result'and s.gold_key then update public.s6_run_state set feedback_text_keys=array['act11.001','act11.011','act11.002','act11.003']where run_id=g.run_id;end if;return result;end$$;

create function public.s6_complete_station_v2(p_room_code text,p_session_token text,p_client_request_id uuid,p_task_value text,p_expected_phase text,p_expected_step int,p_expected_round int)returns jsonb language plpgsql security definer set search_path=public as $$declare p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;role text;prior public.s6_action_receipts%rowtype;result jsonb;payload jsonb:=jsonb_build_object('phase',p_expected_phase,'step',p_expected_step,'round',p_expected_round,'value',p_task_value);begin p:=public.s1_get_player_by_session(upper(trim(p_room_code)),p_session_token);g:=public.s2_get_active_run(upper(trim(p_room_code)));perform public.s6_request_lock(g.run_id,p.player_id,p_client_request_id);select*into prior from public.s6_action_receipts where run_id=g.run_id and player_id=p.player_id and request_id=p_client_request_id;if found then if prior.action_key not in('station_task_v2','station_task')or prior.payload<>payload then raise exception'Request identity reused with different content.';end if;return prior.result||jsonb_build_object('idempotent_replay',true);end if;select*into s from public.s6_run_state where run_id=g.run_id for update;perform public.s6_assert_identity(s,p_expected_phase,p_expected_step,p_expected_round);select role_key into role from public.s6_allocations where run_id=g.run_id and player_id=p.player_id;if role<>'B'then return public.s6_complete_station_guarded(p_room_code,p_session_token,p_client_request_id,p_task_value,p_expected_phase,p_expected_step,p_expected_round);end if;if p_task_value='lever_hold'then insert into public.s6_station_b_progress(run_id,player_id,stage)values(g.run_id,p.player_id,'lever_held')on conflict(run_id)do update set player_id=excluded.player_id,stage='lever_held',held_at=now(),centered_at=null;result:=jsonb_build_object('ok',true,'role_key','B','station_b_stage','lever_held');elsif p_task_value='lever_center'and exists(select 1 from public.s6_station_b_progress where run_id=g.run_id and player_id=p.player_id and stage='lever_held')then update public.s6_station_b_progress set stage='indicator_center',centered_at=now()where run_id=g.run_id;insert into public.s6_station_tasks values(g.run_id,'B',p.player_id,'lever_center',now());result:=jsonb_build_object('ok',true,'role_key','B','task_key','lever_center','station_b_stage','indicator_center');else raise exception'Hold the lever before confirming the center indicator.';end if;insert into public.s6_action_receipts values(g.run_id,p.player_id,p_client_request_id,'station_task_v2',payload,result,now());return result;end$$;

create or replace function public.s6_tick_cinematic(p_run uuid)returns void language plpgsql security definer set search_path=public as $$declare s public.s6_run_state%rowtype;nextstage int;keys text[];audio text;begin select*into s from public.s6_run_state where run_id=p_run for update;if s.phase_key<>'act12_cinematic'or s.stage_started_at+(case when s.cinematic_stage=10 then interval'2 seconds'else interval'1 second'end)>now()then return;end if;nextstage:=s.cinematic_stage+1;keys:=case nextstage when 2 then array['act12.017','act12.018','act12.019']when 3 then(case when s.gold_key then array['act12.020']else array['act12.018']end)when 4 then array['act12.021']when 5 then array['act12.022']when 6 then array['act12.023']when 7 then array['act12.024']when 8 then array['act12.025']when 9 then array['act12.026']when 10 then '{}'::text[]when 11 then '{}'::text[]when 12 then '{}'::text[]else array['act12.027','act13.001','act13.002','act13.003','act02.024']end;audio:=case nextstage when 3 then'audio.snakes_approaching'when 11 then'audio.mechanism_clang'when 12 then'audio.gate_opening'else null end;if nextstage>=13 then update public.s6_run_state set act_no=13,phase_key='act13_escape',cinematic_stage=13,stage_started_at=now(),failure_resolution='cinematic_auto_resolution',mechanism_failure_active=false,escape_success=true,feedback_text_keys=keys,feedback_audio_key=null,updated_at=now()where run_id=p_run;perform public.s6_set_scene(p_run,'act13_escape','act13_escape','castle_exterior','CINEMATIC_MESSAGE','act13.001');else update public.s6_run_state set cinematic_stage=nextstage,stage_started_at=now(),feedback_text_keys=keys,feedback_audio_key=audio,updated_at=now()where run_id=p_run;end if;end$$;

create or replace function public.s6_get_player_state(p_room_code text,p_session_token text)returns jsonb language plpgsql security definer set search_path=public as $$declare room text:=upper(trim(p_room_code));p public.s1_room_players%rowtype;g public.game_runs%rowtype;s public.s6_run_state%rowtype;d public.discussion_sessions%rowtype;begin p:=public.s1_get_player_by_session(room,p_session_token);g:=public.s2_get_active_run(room);perform public.s6_tick_cinematic(g.run_id);select*into s from public.s6_run_state where run_id=g.run_id;if not found then return jsonb_build_object('active',false);end if;select*into d from public.discussion_sessions where run_id=g.run_id and status='discussion'order by vote_round desc limit 1;return jsonb_build_object('active',true,'state',to_jsonb(s),'role_slot',p.role_slot,'scene_asset_key',case when s.act_no=9 then'shared.great_hall'when s.act_no=10 then'prop.golden_key'when s.act_no in(11,12)then'shared.main_gate'when s.act_no=13 then'ending.castle_exterior'end,'discussion',case when d.discussion_session_id is null then null else jsonb_build_object('discussion_session_id',d.discussion_session_id,'phase_key',d.phase_key,'step_key',d.step_key,'vote_round',d.vote_round,'phase_deadline',d.phase_deadline,'silent_texting_mode',d.silent_texting_mode,'messages',(select coalesce(jsonb_agg(jsonb_build_object('display_name',rp.display_name,'message_text',m.message_text,'created_at',m.created_at)order by m.message_id),'[]')from public.dialogue_messages m join public.s1_room_players rp using(player_id)where m.discussion_session_id=d.discussion_session_id))end,'private_clue',(select jsonb_build_object('knowledge_key',knowledge_key,'text_key',text_key)from public.s6_private_clues where run_id=g.run_id and player_id=p.player_id and act_no=s.act_no),'private_choices_revealed',case when s.act_no>10 or s.phase_key in('act10_discussion','act10_final_vote','act10_result')then(select coalesce(jsonb_agg(jsonb_build_object('role_slot',rp.role_slot,'choice_id',c.choice_id)order by rp.role_slot),'[]')from public.s6_choices c join public.s1_room_players rp using(player_id)where c.run_id=g.run_id and c.phase_key='act10_private')else'[]'::jsonb end,'allocation',(select role_key from public.s6_allocations where run_id=g.run_id and player_id=p.player_id),'station_task',(select task_key from public.s6_station_tasks where run_id=g.run_id and player_id=p.player_id),'station_b_stage',(select stage from public.s6_station_b_progress where run_id=g.run_id and player_id=p.player_id),'engaged_roles',(select coalesce(jsonb_agg(role_key),'[]')from public.s6_engagements where run_id=g.run_id),'act13_continue_at',case when s.phase_key='act13_escape'then s.stage_started_at+interval'3 seconds'end,'game_completed',false,'export_ready',false);end$$;

revoke execute on function public.s6_send_message_guarded(text,text,uuid,uuid,text),public.s6_close_discussion_guarded(text,text,text,int,int,uuid),public.s6_submit_group_choice_guarded(text,text,uuid,text,text,int,int),public.s6_submit_private_choice_guarded(text,text,uuid,text,text,int,int),public.s6_advance_guarded(text,text,uuid,text,int,int),public.s6_submit_allocation_guarded(text,text,uuid,text,text,int,int),public.s6_complete_station_guarded(text,text,uuid,text,text,int,int),public.s6_engage_guarded(text,text,uuid,text,text,int,int)from anon,authenticated;
grant execute on function public.s6_send_message_v2(text,text,uuid,uuid,text),public.s6_close_discussion_v2(text,text,uuid,text,int,int,uuid),public.s6_submit_group_choice_v2(text,text,uuid,text,text,int,int),public.s6_submit_private_choice_v2(text,text,uuid,text,text,int,int),public.s6_advance_v2(text,text,uuid,text,int,int),public.s6_submit_allocation_v2(text,text,uuid,text,text,int,int),public.s6_complete_station_v2(text,text,uuid,text,text,int,int),public.s6_engage_v2(text,text,uuid,text,text,int,int)to anon,authenticated;
commit;
